### PR TITLE
publisher articles

### PR DESCRIPTION
**Pull request by ThaboMaibi**
publisher dashboard endpoints only on articles

### CODE REVIEW

**Review by darula-hpp — COMMENTED** [review]
Looks like a lot of code for one commit

**Review by darula-hpp — CHANGES_REQUESTED** [review]
We are supposed to store all media in Azure blob

**Comment by ThaboMaibi** [comment]
i thought the endpoint werent going to be many...so i just continued to add more since they all fall under the same umbrella, hence large amount of code

**Comment by ThaboMaibi** [comment]
alright i have not used it before...i am doing researches....so you dont want images to go to mongodb at all??

**Comment by darula-hpp** [comment]
Let’s discuss more at code review but all our media should go to blob storage, on mongodb we store a link or reference to the resource

**Review by darula-hpp — CHANGES_REQUESTED** [review]
please put the .env in a gitignore it is exposed

**Pull request merged**
